config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :owners
  root 'pages#index'
  get '/developer' => 'pages#developer'
  get '/food_options' => 'foods#options'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :products

  belongs_to :category
end

app/models/owner.rb
# frozen_string_literal: true
class Owner < ApplicationRecord
  validates :fname, :lname, presence: true, length: {maximum: 30}
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+([_ -.]?[a-zA-Z0-9])*\z/
  validates :username, presence: true, length: {maximum: 60}, uniqueness: {case_sensitive: false},
            format: {with: VALID_USERNAME_REGEX}
  has_many :products

end

app/models/product.rb
class Product < ApplicationRecord
  enum units: %i[gram
                 kilogram
                 ounce
                 pound]

  validates :name, presence: true, length: {maximum: 60}
  validates :amount, presence: true, length: {maximum: 10}
  validates :units, :purchase_date, :expiration_date, presence: true

  belongs_to :owner
  belongs_to :category
  belongs_to :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action only: [:options]

  def options
    if params[:category_id]
      foods = Food.where(category_id: params[:category_id])
      options = foods.collect {|food| "\"#{food.id}\" : \"#{food.title}\""}
    else
      categories = Category.all
      options = categories.collect {|category| "\"#{category.id}\" : \"#{category.title}\""}
    end

    render json: "{#{options.join(",")}}"
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def foods_params

    params.require(:category_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
    respond_to do |format|
      format.html {render :index}
      format.json {render :index, status: :ok}
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_owner
    @owner = Owner.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def owner_params
    params.require(:owner).permit(:fname, :lname, :username)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def developer
  end

  def dashboard
  end

  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_units

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_to do |format|
      format.html {render :index}
      format.json {render :index, status: :ok}
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    if Owner.all.first.nil?
      redirect_to owners_url, error_message: 'You need to create a user first!'
    else
      @product = Product.new
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    owner = Owner.find(product_params[:owner_id])
    category = Category.find(product_params[:category_id])
    food = Food.find(product_params[:food_id])
    @product.build_owner(id: owner.id)

    respond_to do |format|
      if @product.save
        format.html {redirect_to @product, notice: 'Product was successfully created.'}
        format.json {render :show, status: :created, location: @product}
      else
        format.html {render :new}
        format.json {render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html {redirect_to @product, notice: 'Product was successfully updated.'}
        format.json {render :show, status: :ok, location: @product}
      else
        format.html {render :edit}
        format.json {render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html {redirect_to products_url, notice: 'Product was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :purchase_date, :owner_id, :expiration_date, :category_id, :food_id, :amount, :units)
  end

  def set_units
    @units = Product.units
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue-text text-darken-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12 left-align">
        <h5 class="white-text">About me</h5>
        <p class="grey-text text-lighten-4">I'm a computer engineer who loves to make new things and tries to keep things clean as much as he can. This idea started as a final project for one of my classes at Grand Valley State University.</p>
      </div>
      <div class="col l6 s12 right-align">
        <h5 class="white-text">More</h5>
        <ul>
          <li>
            <a class="white-text" href="https://raulolmedo.com">My personal web page</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <i class="fas fa-code"></i>
      <span>with</span>
      <a class="pink-text text-lighten-3" href="https://materializecss.com">Materialize</a>
      <span>&</span>
      <a class="red-text text-lighten-2" href="https://rubyonrails.org">Ruby On Rails</a>
      <div class="right">
        <span>See this project on</span>
        <a href="https://github.com/olmedocr/make-your-fridge-great-again"><i class="fab fa-github fa-lg white-text"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="nav-extended white">
      <div class="nav-wrapper container">
        <a id="logo-container" class="brand-logo" href=<%= root_path %>>MYFGA</a>
        <ul class="right hide-on-med-and-down">
          <!-- Links on desktop nav -->
          <li>
            <a class="uppercase" href=<%= products_path %>>Products</a>
          </li>
          <li>
            <a class="uppercase" href=<%= owners_path %>>Owners</a>
          </li>
          <li>
            <a class="uppercase" href=<%= developer_path %>>Developer</a>
          </li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger">
          <i class="material-icons light-blue-text text-darken-4">menu</i>
        </a>
      </div>

      <%= yield :nav_content %>
    </nav>
  </div>

  <ul id="nav-mobile" class="sidenav">
    <!-- Links on mobile nav -->
    <li>
      <a class="uppercase" href=<%= products_path %>>Products</a>
    </li>
    <li>
      <a class="uppercase" href=<%= owners_path %>>Owners</a>
    </li>
    <li>
      <a class="uppercase" href=<%= developer_path %>>Developer</a>
    </li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakeYourFridgeGreatAgain</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://use.fontawesome.com/releases/v5.8.1/js/all.js" data-mutate-approach="sync"></script>

</head>

<body>
<%= render 'layouts/nav' %>

<% if controller_name == 'pages' && action_name == 'index' %>
  <main>
    <%= yield %>
  </main>
<% else %>
  <main class="container">
    <%= yield %>
  </main>
<% end %>

<br>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_with(model: owner, local: true) do |form| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
        <% owner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fixed-action-btn">
    <%= form.submit "OK", class: "btn-floating btn-large red"  %>
  </div>

  <div class="row">
    <div class="input-field col s12 m6 offset-m3">
      <% if owner.new_record? %>
        <%= form.label :fname %>
      <% else %>
        <%= form.label :fname, class: "active" %>
      <% end %>
      <%= form.text_field :fname %>
    </div>

    <div class="input-field col s12 m6 offset-m3">
      <% if owner.new_record? %>
        <%= form.label :lname %>
      <% else %>
        <%= form.label :lname, class: "active" %>
      <% end %>
      <%= form.text_field :lname %>
    </div>

    <div class="input-field col s12 m6 offset-m3">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, owners_path, class: 'btn' %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<div class="fixed-action-btn">
  <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_owner_path, :class => "btn-floating pulse btn-large red" %>
</div>

<div class="row">
  <!-- TODO: centrar el nombre en mobile (classics) y esto tambien -->
  <% @owners.each do |owner| %>
    <div class="col s10 m6 l4 offset-s1">
      <div class="card">
        <div class="card-image">
          <img alt="placeholder" src=<%= image_url("Placeholder-Portrait.jpg") %>>
        </div>
        <div class="card-content">
          <span class="card-title uppercase"><%= "#{owner.fname} #{owner.lname}" %></span>
          <p class="grey-text"><%= "@#{owner.username}" %></p>
        </div>
        <div class="card-action center-align">
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">info_outline</i>'.html_safe, owner %>
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">edit</i>'.html_safe, edit_owner_path(owner) %>
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">delete</i>'.html_safe, owner, method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, owners_path, class: 'btn' %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<div class="fixed-action-btn">
  <%= link_to '<i class="large material-icons">edit</i>'.html_safe, edit_owner_path(@owner), :class => "btn-floating btn-large red" %>
</div>

<div class="row">
  <div class="col s10 m6 offset-s1 offset-m3">
    <ul class="collection">
      <li class="collection-item"><div>First name<span class="secondary-content"><%= @owner.fname %></span></div></li>
      <li class="collection-item"><div>Last name<span class="secondary-content"><%= @owner.lname %></span></div></li>
      <li class="collection-item"><div>Username<span class="secondary-content"><%= @owner.username %></span></div></li>
    </ul>
  </div>
</div>

<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, owners_path, class: 'btn' %>

app/views/pages/developer.html.erb
<p id="notice"><%= notice %></p>

<h1>Developer</h1>

<h3>Endpoints</h3>
<p> You can retrieve several things from the server by making a GET petition to the following endpoints (click to
  reveal).
  All responses from the server are in JSON.</p>

<ul class="collapsible">
  <li>
    <div class="collapsible-header light-blue darken-4 white-text">Owners</div>
    <div class="collapsible-body">
      <ul>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/owners.json</code>
          <h5>Example response</h5>
          <pre><code>
            [{
                "id": 6,
                "fname": "Raul",
                "lname": "Olmedo",
                "username": "olmedocr",
                "url": "http://0.0.0.0:3000/owners/6.json"
              },
              {
                "id": 8,
                "fname": "Sergio",
                "lname": "Cabañas",
                "username": "cabanass",
                "url": "http://0.0.0.0:3000/owners/8.json"
              }]
          </code></pre>
        </li>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/owner/id.json</code>
          <p>Query parameter: <code>id</code></p>
          <h5>Example response</h5>
          <pre><code>
            {
              "id": 6,
              "fname": "Raul",
              "lname": "Olmedo",
              "username": "olmedocr",
              "url": "http://0.0.0.0:3000/owners/6.json"
            }
          </code></pre>
        </li>
      </ul>
    </div>
  </li>
  <li>
    <div class="collapsible-header light-blue darken-4 white-text">Products</div>
    <div class="collapsible-body">
      <ul>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/products.json</code>
          <h5>Example response</h5>
          <pre><code>
            [
              {
                "id": 6,
                "name": "Domino's pizza",
                "owner_id": 6,
                "purchase_date": "2019-04-09",
                "expiration_date": "2019-04-15",
                "category_id": 9,
                "food_id": 17,
                "amount": 240,
                "units": "gram",
                "url": "http://0.0.0.0:3000/products/6.json"
              },
              {
                "id": 9,
                "name": "Stir fry noodles",
                "owner_id": 6,
                "purchase_date": "2019-04-24",
                "expiration_date": "2019-04-28",
                "category_id": 9,
                "food_id": 17,
                "amount": 240,
                "units": "gram",
                "url": "http://0.0.0.0:3000/products/6.json"
              }
            ]
          </code></pre>
        </li>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/product/id.json</code>
          <p>Query parameter: <code>id</code></p>
          <h5>Example response</h5>
          <pre><code>
            {
                "id": 6,
                "name": "Domino's pizza",
                "owner_id": 6,
                "purchase_date": "2019-04-09",
                "expiration_date": "2019-04-15",
                "category_id": 9,
                "food_id": 17,
                "amount": 240,
                "units": "gram",
                "url": "http://0.0.0.0:3000/products/6.json"
            }
          </code></pre>
        </li>
      </ul>
    </div>
  </li>
  <li>
    <div class="collapsible-header light-blue darken-4 white-text">Food categories (I)</div>
    <div class="collapsible-body">
      <ul>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/food_options.json</code>
          <h5>Example response</h5>
          <pre><code>
            {
              "1": "Salads",
              "2": "Hot dogs",
              "3": "Luncheon meat",
              "4": "Bacon & Sausage",
              "5": "Hamburger & Other Ground Meats",
              "6": "Fresh Beef, Veal, Lamb & Pork",
              "7": "Fresh Poultry",
              "8": "Soups & Stews",
              "9": "Leftovers"
            }
          </code></pre>
        </li>
      </ul>
    </div>
  </li>
  <li>
    <div class="collapsible-header light-blue darken-4 white-text">Food categories (II)</div>
    <div class="collapsible-body">
      <ul>
        <li>
          <h5>Endpoint</h5>
          <code><%= request.base_url %>/food_options?category_id=id.json</code>
          <p>Query parameter: <code>id</code></p>
          <p>This parameter must match one of the ids in the previous food_options json response</p>
          <h5>Example response</h5>
          <pre><code>
            {
              "4": "opened package or deli sliced",
              "5": "unopened package"
            }
          </code></pre>
        </li>
      </ul>
    </div>
  </li>
</ul>

<h3>How the food categories work?</h3>
<p>The estimated expiry date can be computed by getting the category first and then query the server with that id to get
  the list of foods under that category.</p>


<h3>Where's the AJAX?</h3>
<p>When a new product is created the food dropdown shows the 9 main categories, after selecting one the web app does an
  AJAX request on itself to gather all the foods that are under that same category to finally display them as options on
  the selector.</p>


<h3>How to solve JQuery - Materialize - Turbolinks problem</h3>
<p>After spending countless hours trying to make JavaScript/CoffeeScript work under Turbolinks, here's my solution to
  add JavaScript code (with Materialize components) that gets executed every time the page is loaded. Since maybe
  there's more people out there using Ruby on Rails with Materialize too, the following examples will show how to
  initialize and destroy Materialized components, but this solution also applies to the use of JQuery under
  Turbolinks.</p>
<pre><code>
$(document).on 'turbolinks:load', ->
  # Setup sidenav
  $('.sidenav').sidenav()

  return

$(document).on 'turbolinks:before-cache', ->
  # Destroy sidenav
  sidenav = $('.sidenav')
  sidenavInstance = M.Sidenav.getInstance(sidenav)
  sidenavInstance.destroy()

  return
</code></pre>
<p>So what this CoffeeScript snippet does is set a listener for when turbolinks loads the page (what in vanilla HTML/JS
  would be the 'onload' event of the window). The second part is only required while using Materialized component
  system.</p>

app/views/pages/index.html.erb
<% content_for :nav_content do %>
  <!-- TODO: do this sticky (with pushpin) && scrollspy-->
  <!-- TODO: add bar at bottom of tabs -->
  <!-- TODO: add shadow like on the navbar -->
  <div class="nav-content container">
    <ul class="tabs">
      <li class="tab">
        <a class="active" href="#parallax1">Home</a>
      </li>
      <li class="tab">
        <a href="#section1">Top functionalities</a>
      </li>
      <li class="tab">
        <a href="#section2">Why?</a>
      </li>
      <!-- TODO: add ad the bottom a line to show the selected tab (like in a tab component) -->
    </ul>
  </div>
<% end %>

<div id="parallax1" class="parallax-container scrollspy">
  <div class="section no-pad-bot">
    <div class="container">
      <br>
      <br>
      <h1 class="header center">MYFGA</h1>
      <div class="row center">
        <h5 class="header col s12">Make Your Fridge Great Again!</h5>
      </div>
      <div class="row center">
        <a class="btn-large waves-effect waves-light light-blue darken-4" href=<%= owners_path %>>Get
          Started</a>
      </div>
    </div>
  </div>
  <div class="parallax">
    <img alt="Unsplashed background img 1" src=<%= image_url("background1.jpg") %>>
  </div>
</div>
<div id="section1" class="scrollspy container">
  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text text-darken-4">
            <i class="material-icons">flash_on</i>
          </h2>
          <h5 class="center">Keep it clean</h5>
          <p class="light">Go to the products section to see if there's something about to expire, maybe you want to prepare
            that delicious meal again before it goes bad.</p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text text-darken-4">
            <i class="material-icons">group</i>
          </h2>
          <h5 class="center">Manage users</h5>
          <p class="light">Get at a glance who bough what, just in case you have to throw it away.</p>
          <p class="light"></p>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text text-darken-4">
            <i class="material-icons">settings</i>
          </h2>
          <h5 class="center">Build your own solution</h5>
          <p class="light">This web app provides an API to interact with the built in database and manage all products
            and users.</p>
          <p class="light">Visit the developers page and start building something cool today!</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="parallax2" class="scrollspy parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">Because not all leftovers deserve to get thrown away</h5>
      </div>
    </div>
  </div>
  <div class="parallax">
    <img alt="Unsplashed background img 2" src=<%= image_url("background2.jpg") %>>
  </div>
</div>
<div id="section2" class="scrollspy container">
  <div class="section">
    <div class="row">
      <div class="col s12 center">
        <h3>
          <i class="mdi-content-send brown-text"></i>
        </h3>
        <h4>Why does this exist?</h4>
        <p class="left-align light">One of the key parts in cooking rests in how much quantity do you make (we all have
          done THAT amount of pasta). It's common to cook more than needed, maybe because of the followed recipe or a
          last change of plans, either way you should be able to keep track of whats on your fridge, and when it's no
          longer safe to consume. </p>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, products_path, class: 'btn' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="fixed-action-btn">
    <%= link_to '<i class="large material-icons">add</i>'.html_safe, new_product_path, :class => "btn-floating pulse btn-large red" %>
</div>

<div class="row">
  <!-- TODO: centrar el nombre en mobile (classics) y esto tambien -->
  <% @products.each do |product| %>
    <div class="col s8 m6 l4 offset-s2 ">
      <div class="card">
        <div class="card-content">
          <span class="card-title"><%= product.name %></span>
          <p class="grey-text"><%= product.owner.try(:username) || "NA" %></p>
        </div>
        <div class="card-tabs">
          <ul class="tabs tabs-fixed-width">
            <li class="tab"><a href=<%= "#purchase_date_#{product.id}" %>>Purch. date</a></li>
            <li class="tab"><a href=<%= "#expiration_date_#{product.id}" %>>Exp. date</a></li>
          </ul>
        </div>
        <div class="card-content grey lighten-4">
          <div id=<%= "purchase_date_#{product.id}" %>><%= product.purchase_date %></div>
          <div id=<%= "expiration_date_#{product.id}" %>><%= product.expiration_date %></div>
        </div>
        <div class="card-action center-align">
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">info_outline </i>'.html_safe, product %>
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">edit</i>'.html_safe, edit_product_path(product) %>
          <%= link_to '<i class="material-icons light-blue-text text-darken-4">delete</i>'.html_safe, product, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, products_path, class: 'btn' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="fixed-action-btn">
  <%= link_to '<i class="large material-icons">edit</i>'.html_safe, edit_product_path(@product), :class => "btn-floating btn-large red" %>
</div>

<div class="row">
  <div class="col s10 m6 offset-s1 offset-m3">
    <ul class="collection">
      <li class="collection-item"><div>Product<span class="secondary-content"><%= @product.name %></span></div></li>
      <li class="collection-item"><div>Owner<span class="secondary-content"><%= @product.owner.try(:username) || "NA" %></span></div></li>
      <li class="collection-item"><div>Purchase date<span class="secondary-content"><%= @product.purchase_date %></span></div></li>
      <li class="collection-item"><div>Expiration date<span class="secondary-content"><%= @product.expiration_date %></span></div></li>
      <li class="collection-item"><div>Category<span class="secondary-content"><%= (@product.category.try(:title) || "NA") %></span></div></li>
      <li class="collection-item"><div>Food<span class="secondary-content"><%= (@product.food.try(:title) || "NA") %></span></div></li>
      <li class="collection-item"><div>Amount<span class="secondary-content"><%= @product.amount %></span></div></li>
      <li class="collection-item"><div>Units<span class="secondary-content"><%= @product.units %></span></div></li>
    </ul>
  </div>
</div>



<%= link_to '<i class="material-icons">arrow_back</i>'.html_safe, products_path, class: 'btn' %>